name: Update and Release Launcher

on:
  push:
    branches:
      - develop

jobs:
  update_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Launcher Repository
        uses: actions/checkout@v2
          
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ELN_mod
          repo: axalppro/ElectricalAge
          workflow: main.yml
          path: ./.minecraft/mods
          search_artifacts: true

      - name: Check correct files
        run: ls ./.minecraft/mods

      - name: Create release
        uses: ncipollo/release-action@v1
        
